### ISSUE TITLE
Delete 'yum' before 'apt-get' on line 3

### ISSUE THREAD

**Issue by gdelanoy** [gorect/Proxmox#2]
https://github.com/gorect/Proxmox/blob/5b6941140013f4a8be307b8b4931291ef1ed29e2/Enable-QEMU-Guest-Agent/qemu-guest-agent-debian.sh#L3

**Comment by gdelanoy** [comment]
must be a 'copy'n paste' skid ;)

**Comment by gorect** [comment]
Thanks!
